version: "3"

services:
  server:
    container_name: server
    build:
      context: .
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    links:
      - mysql
    volumes:
      - ./app:/app
#    env_file:
#      - proxy.env
#    environment:
#      http_proxy: "http://proxy.nagaokaut.ac.jp:8080"
#      https_proxy: "http://proxy.nagaokaut.ac.jp:8080"
